# Generated by Django 5.2.1 on 2025-09-07 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canteenApp', '0009_coursevideo_notes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessageAi',
        ),
    ]
