# Generated by Django 5.2.1 on 2025-09-07 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canteenApp', '0012_chatmessageuserai_delete_chatmessageai'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessageUserAI',
        ),
    ]
